version: "3.9"

services:
  # Contenedor frontend
  frontend:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    container_name: frontendVideoChat
    ports: 
      - "5173:5173"
    volumes:
      - ./cliente:/app
    restart: unless-stopped

  # Contenedor backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin_videochat
      - DB_PASSWORD=123456789
      - DB_NAME=videochat
    volumes:
      - ./server:/app
      - ./certs:/app/certs
    command: npm run dev
    restart: unless-stopped

  # Contenedor base de datos
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin_videochat
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: videochat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
